-- ============================================
-- 물류센터 직접 입고 관리 테이블 생성
-- ============================================

-- 1. 시퀀스 생성
CREATE SEQUENCE TB_LOGISTICS_DIRECT_RETURN_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCYCLE
    CACHE 20;

-- 2. 테이블 생성
CREATE TABLE TB_LOGISTICS_DIRECT_RETURN (
    -- 기본 정보
    DIRECT_RETURN_ID NUMBER NOT NULL,
    RECEIVED_DATE DATE NOT NULL,                    -- 입고일자 (물류센터 실제 입고일)
    SITE_NAME VARCHAR2(100),                       -- 사이트/브랜드명
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,          -- 고객명
    CUSTOMER_PHONE VARCHAR2(20),                   -- 고객 연락처
    
    -- 상품 정보
    PRODUCT_CODE VARCHAR2(100),                    -- 제품코드
    PRODUCT_COLOR VARCHAR2(50),                    -- 색상
    PRODUCT_SIZE VARCHAR2(50),                     -- 사이즈
    QUANTITY NUMBER(3,0) DEFAULT 1 NOT NULL,      -- 수량
    
    -- 배송 정보
    TRACKING_NUMBER VARCHAR2(100),                 -- 운송장번호 (매핑 키)
    COURIER_COMPANY VARCHAR2(50),                  -- 택배사
    
    -- 처리 정보
    REMARKS VARCHAR2(1000),                        -- 특이사항/메모
    PROCESSING_STATUS VARCHAR2(20) DEFAULT 'RECEIVED' NOT NULL, -- 처리상태 (RECEIVED:입고완료, PROCESSED:처리완료)
    
    -- 기존 교환반품과 매핑
    MATCHED_RETURN_ID NUMBER,                      -- TB_RETURN_ITEM.RETURN_ID와 연결
    MAPPING_STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL, -- 매핑상태 (PENDING:미매핑, MATCHED:매핑완료, UNMATCHED:매핑불가)
    MAPPING_DATE TIMESTAMP,                       -- 매핑 완료일시
    MAPPING_BY VARCHAR2(50),                      -- 매핑 처리자
    
    -- 시스템 관리
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50),
    
    -- 제약조건
    CONSTRAINT PK_LOGISTICS_DIRECT_RETURN PRIMARY KEY (DIRECT_RETURN_ID),
    CONSTRAINT FK_LOGISTICS_MATCHED_RETURN FOREIGN KEY (MATCHED_RETURN_ID) 
        REFERENCES TB_RETURN_ITEM(RETURN_ID),
    CONSTRAINT CHK_MAPPING_STATUS CHECK (MAPPING_STATUS IN ('PENDING', 'MATCHED', 'UNMATCHED')),
    CONSTRAINT CHK_PROCESSING_STATUS CHECK (PROCESSING_STATUS IN ('RECEIVED', 'PROCESSED'))
);

-- 3. 인덱스 생성
CREATE INDEX IDX_LOGISTICS_TRACKING_NUMBER ON TB_LOGISTICS_DIRECT_RETURN(TRACKING_NUMBER);
CREATE INDEX IDX_LOGISTICS_CUSTOMER_NAME ON TB_LOGISTICS_DIRECT_RETURN(CUSTOMER_NAME);
CREATE INDEX IDX_LOGISTICS_RECEIVED_DATE ON TB_LOGISTICS_DIRECT_RETURN(RECEIVED_DATE);
CREATE INDEX IDX_LOGISTICS_MAPPING_STATUS ON TB_LOGISTICS_DIRECT_RETURN(MAPPING_STATUS);
CREATE INDEX IDX_LOGISTICS_MATCHED_RETURN_ID ON TB_LOGISTICS_DIRECT_RETURN(MATCHED_RETURN_ID);

-- 4. 테이블 코멘트
COMMENT ON TABLE TB_LOGISTICS_DIRECT_RETURN IS '물류센터 직접 입고 관리 테이블';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.DIRECT_RETURN_ID IS '직접입고 고유ID';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.RECEIVED_DATE IS '입고일자 (물류센터 실제 입고일)';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.SITE_NAME IS '사이트/브랜드명';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.CUSTOMER_NAME IS '고객명';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.CUSTOMER_PHONE IS '고객 연락처';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.PRODUCT_CODE IS '제품코드';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.PRODUCT_COLOR IS '색상';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.PRODUCT_SIZE IS '사이즈';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.QUANTITY IS '수량';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.TRACKING_NUMBER IS '운송장번호 (기존 교환반품과 매핑용)';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.COURIER_COMPANY IS '택배사';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.REMARKS IS '특이사항/메모';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.PROCESSING_STATUS IS '처리상태 (RECEIVED:입고완료, PROCESSED:처리완료)';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.MATCHED_RETURN_ID IS '매핑된 교환반품 ID (TB_RETURN_ITEM.RETURN_ID)';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.MAPPING_STATUS IS '매핑상태 (PENDING:미매핑, MATCHED:매핑완료, UNMATCHED:매핑불가)';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.MAPPING_DATE IS '매핑 완료일시';
COMMENT ON COLUMN TB_LOGISTICS_DIRECT_RETURN.MAPPING_BY IS '매핑 처리자';

-- 5. 샘플 데이터 (테스트용)
INSERT INTO TB_LOGISTICS_DIRECT_RETURN (
    DIRECT_RETURN_ID, RECEIVED_DATE, SITE_NAME, CUSTOMER_NAME, CUSTOMER_PHONE,
    PRODUCT_CODE, PRODUCT_COLOR, PRODUCT_SIZE, QUANTITY,
    TRACKING_NUMBER, COURIER_COMPANY, REMARKS,
    CREATED_BY, UPDATED_BY
) VALUES (
    TB_LOGISTICS_DIRECT_RETURN_SEQ.NEXTVAL,
    SYSDATE,
    '29CM-레노마',
    '김고객',
    '010-1234-5678',
    'RN2024001',
    '블랙',
    'L',
    1,
    '1234567890123',
    'CJ대한통운',
    '교환 요청 상품, 택 제거됨',
    'SYSTEM',
    'SYSTEM'
);

COMMIT;

-- 6. 권한 부여 (필요시)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON TB_LOGISTICS_DIRECT_RETURN TO [사용자명];

-- 7. 확인 쿼리
SELECT 
    DIRECT_RETURN_ID,
    RECEIVED_DATE,
    SITE_NAME,
    CUSTOMER_NAME,
    PRODUCT_CODE,
    TRACKING_NUMBER,
    MAPPING_STATUS,
    CREATED_DATE
FROM TB_LOGISTICS_DIRECT_RETURN
ORDER BY DIRECT_RETURN_ID DESC; 