-- 사이트 마스터 테이블 생성
CREATE TABLE TB_SITE_MASTER (
    SITE_ID         NUMBER(10,0)     NOT NULL,
    BRAND           VARCHAR2(20)     NOT NULL,
    SITE_NAME       VARCHAR2(100)    NOT NULL,
    SITE_CODE       VARCHAR2(50)     NOT NULL,
    ACTIVE_YN       CHAR(1)          DEFAULT 'Y' NOT NULL,
    SORT_ORDER      NUMBER(3,0)      DEFAULT 0,
    CREATED_DATE    DATE             DEFAULT SYSDATE NOT NULL,
    UPDATED_DATE    DATE             DEFAULT SYSDATE,
    CONSTRAINT PK_TB_SITE_MASTER PRIMARY KEY (SITE_ID),
    CONSTRAINT UK_TB_SITE_MASTER UNIQUE (BRAND, SITE_CODE),
    CONSTRAINT CK_TB_SITE_BRAND CHECK (BRAND IN ('RENOMA', 'CORALIQUE')),
    CONSTRAINT CK_TB_SITE_ACTIVE CHECK (ACTIVE_YN IN ('Y', 'N'))
);

-- 시퀀스 생성
CREATE SEQUENCE SEQ_SITE_MASTER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 인덱스 생성
CREATE INDEX IDX_TB_SITE_BRAND ON TB_SITE_MASTER(BRAND, ACTIVE_YN);
CREATE INDEX IDX_TB_SITE_ORDER ON TB_SITE_MASTER(BRAND, SORT_ORDER);

-- 테이블 코멘트
COMMENT ON TABLE TB_SITE_MASTER IS '사이트 마스터 테이블';
COMMENT ON COLUMN TB_SITE_MASTER.SITE_ID IS '사이트 ID (PK)';
COMMENT ON COLUMN TB_SITE_MASTER.BRAND IS '브랜드 (RENOMA, CORALIQUE)';
COMMENT ON COLUMN TB_SITE_MASTER.SITE_NAME IS '사이트명 (표시용)';
COMMENT ON COLUMN TB_SITE_MASTER.SITE_CODE IS '사이트 코드 (시스템용)';
COMMENT ON COLUMN TB_SITE_MASTER.ACTIVE_YN IS '활성화 여부 (Y/N)';
COMMENT ON COLUMN TB_SITE_MASTER.SORT_ORDER IS '정렬 순서';
COMMENT ON COLUMN TB_SITE_MASTER.CREATED_DATE IS '생성일시';
COMMENT ON COLUMN TB_SITE_MASTER.UPDATED_DATE IS '수정일시';

-- 초기 데이터 삽입 - RENOMA
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '자사몰-레노마', 'RENOMA_OFFICIAL', 1);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '톡스토어-레노마', 'RENOMA_TOK', 2);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '11번가-레노마', 'RENOMA_11ST', 3);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', 'SSG-레노마', 'RENOMA_SSG', 4);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', 'W컨셉-레노마', 'RENOMA_WCONCEPT', 5);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '하프클럽-레노마', 'RENOMA_HALFCLUB', 6);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '패션플러스-레노마', 'RENOMA_FASHIONPLUS', 7);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '퀸잇-레노마', 'RENOMA_QUEENIT', 8);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '무신사-레노마', 'RENOMA_MUSINSA', 9);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '롯데온-레노마', 'RENOMA_LOTTEON', 10);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '지그재그-레노마', 'RENOMA_ZIGZAG', 11);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '29CM-레노마', 'RENOMA_29CM', 12);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'RENOMA', '스토어팜-레노마', 'RENOMA_STOREFARM', 13);

-- 초기 데이터 삽입 - CORALIQUE
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', '자사몰-코랄리크', 'CORALIQUE_OFFICIAL', 1);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', '29CM-코랄리크', 'CORALIQUE_29CM', 2);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', '무신사-코랄리크', 'CORALIQUE_MUSINSA', 3);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', '지그재그-코랄리크', 'CORALIQUE_ZIGZAG', 4);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', 'CJ오쇼핑-코랄리크', 'CORALIQUE_CJMALL', 5);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', 'SSG-코랄리크', 'CORALIQUE_SSG', 6);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', 'EQL-코랄리크', 'CORALIQUE_EQL', 7);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', 'LF몰-코랄리크', 'CORALIQUE_LFMALL', 8);
INSERT INTO TB_SITE_MASTER (SITE_ID, BRAND, SITE_NAME, SITE_CODE, SORT_ORDER) VALUES (SEQ_SITE_MASTER.NEXTVAL, 'CORALIQUE', '스토어팜-코랄리크', 'CORALIQUE_STOREFARM', 9);

-- 커밋
COMMIT;

-- 확인 쿼리
SELECT BRAND, SITE_NAME, SITE_CODE, SORT_ORDER, ACTIVE_YN
FROM TB_SITE_MASTER 
ORDER BY BRAND, SORT_ORDER; 