-- 상담 문의 테이블
CREATE TABLE CONSULTING_INQUIRY (
    INQUIRY_ID NUMBER PRIMARY KEY,
    CUSTOMER_NAME VARCHAR2(100) NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    ORDER_NUMBER VARCHAR2(50),
    INQUIRY_TYPE VARCHAR2(30) NOT NULL,
    INQUIRY_CONTENT CLOB NOT NULL,
    PROCESS_CONTENT CLOB,
    STATUS VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
    ASSIGNED_TO VARCHAR2(50),
    MEMO CLOB,
    IMAGE_URL VARCHAR2(255),
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50)
);

-- 상담 문의 시퀀스
CREATE SEQUENCE SEQ_CONSULTING_INQUIRY
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 자주 쓰는 응답 템플릿 테이블
CREATE TABLE COMMON_REPLY_TEMPLATE (
    ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    CONTENT CLOB NOT NULL,
    CATEGORY VARCHAR2(30) NOT NULL,
    DISPLAY_ORDER NUMBER DEFAULT 0 NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CREATED_BY VARCHAR2(50),
    UPDATED_BY VARCHAR2(50)
);

-- 응답 템플릿 시퀀스
CREATE SEQUENCE SEQ_COMMON_REPLY_TEMPLATE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 문의 첨부파일 테이블
CREATE TABLE INQUIRY_ATTACHMENT (
    ATTACHMENT_ID NUMBER PRIMARY KEY,
    INQUIRY_ID NUMBER NOT NULL,
    FILE_NAME VARCHAR2(255) NOT NULL,
    FILE_PATH VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER NOT NULL,
    FILE_TYPE VARCHAR2(100) NOT NULL,
    IS_MAIN_IMAGE NUMBER(1) DEFAULT 0 NOT NULL,
    UPLOAD_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ATTACHMENT_INQUIRY FOREIGN KEY (INQUIRY_ID) 
        REFERENCES CONSULTING_INQUIRY (INQUIRY_ID) ON DELETE CASCADE
);

-- 첨부파일 시퀀스
CREATE SEQUENCE SEQ_INQUIRY_ATTACHMENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 문의 코멘트 테이블
CREATE TABLE INQUIRY_COMMENT (
    COMMENT_ID NUMBER PRIMARY KEY,
    INQUIRY_ID NUMBER NOT NULL,
    CONTENT CLOB NOT NULL,
    COMMENTER VARCHAR2(50) NOT NULL,
    COMMENT_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    IS_INTERNAL NUMBER(1) DEFAULT 0 NOT NULL,
    CONSTRAINT FK_COMMENT_INQUIRY FOREIGN KEY (INQUIRY_ID) 
        REFERENCES CONSULTING_INQUIRY (INQUIRY_ID) ON DELETE CASCADE
);

-- 코멘트 시퀀스
CREATE SEQUENCE SEQ_INQUIRY_COMMENT
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 문의 유형별 주의사항 테이블
CREATE TABLE NOTICE_BY_INQUIRY_TYPE (
    NOTICE_ID NUMBER PRIMARY KEY,
    INQUIRY_TYPE VARCHAR2(30) NOT NULL,
    NOTICE_CONTENT CLOB NOT NULL,
    IS_ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CREATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_NOTICE_INQUIRY_TYPE UNIQUE (INQUIRY_TYPE)
);

-- 주의사항 시퀀스
CREATE SEQUENCE SEQ_NOTICE_BY_INQUIRY_TYPE
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- 공통 코드 테이블 확인 (없는 경우 생성)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM USER_TABLES WHERE TABLE_NAME = 'COMMON_CODE';
    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
        CREATE TABLE COMMON_CODE (
            CODE_ID NUMBER PRIMARY KEY,
            CODE_GROUP VARCHAR2(30) NOT NULL,
            CODE VARCHAR2(30) NOT NULL,
            CODE_NAME VARCHAR2(100) NOT NULL,
            DESCRIPTION VARCHAR2(500),
            SORT_ORDER NUMBER DEFAULT 0 NOT NULL,
            USE_YN CHAR(1) DEFAULT ''Y'' NOT NULL,
            CONSTRAINT UK_COMMON_CODE UNIQUE (CODE_GROUP, CODE)
        )';
        
        EXECUTE IMMEDIATE '
        CREATE SEQUENCE SEQ_COMMON_CODE
            START WITH 1
            INCREMENT BY 1
            NOCACHE
            NOCYCLE';
    END IF;
END;
/

-- 문의 유형 코드 등록
INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'PRODUCT', '상품 문의', '상품 관련 문의', 1, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'PRODUCT');

INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'DELIVERY', '배송 문의', '배송 관련 문의', 2, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'DELIVERY');

INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'REFUND', '환불 문의', '환불 관련 문의', 3, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'REFUND');

INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'EXCHANGE', '교환 문의', '교환 관련 문의', 4, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'EXCHANGE');

INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'DEFECT', '불량 문의', '상품 불량 관련 문의', 5, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'DEFECT');

INSERT INTO COMMON_CODE (CODE_ID, CODE_GROUP, CODE, CODE_NAME, DESCRIPTION, SORT_ORDER, USE_YN)
SELECT SEQ_COMMON_CODE.NEXTVAL, 'INQUIRY_TYPE', 'OTHER', '기타 문의', '기타 문의 사항', 6, 'Y' FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_CODE WHERE CODE_GROUP = 'INQUIRY_TYPE' AND CODE = 'OTHER');

-- 기본 응답 템플릿 등록
INSERT INTO COMMON_REPLY_TEMPLATE (ID, TITLE, CONTENT, CATEGORY, DISPLAY_ORDER, IS_ACTIVE, CREATED_DATE, UPDATED_DATE)
SELECT SEQ_COMMON_REPLY_TEMPLATE.NEXTVAL, '배송 안내', 
       '안녕하세요. 고객님
       
문의하신 상품의 배송 관련하여 안내드립니다.

일반적으로 결제 완료 후 1-2일 이내에 출고되며, 택배사 사정에 따라 2-3일 정도 소요될 수 있습니다.
현재 고객님의 주문은 정상적으로 처리 중이며, 빠른 시일 내에 배송될 예정입니다.

추가 문의사항이 있으시면 언제든지 연락주시기 바랍니다.
감사합니다.', 
       '배송', 1, 1, SYSTIMESTAMP, SYSTIMESTAMP FROM DUAL
WHERE NOT EXISTS (SELECT 1 FROM COMMON_REPLY_TEMPLATE WHERE TITLE = '배송 안내' AND CATEGORY = '배송');

INSERT INTO COMMON_REPLY_TEMPLATE (ID, TITLE, CONTENT, CATEGORY, DISPLAY_ORDER, IS_ACTIVE, CREATED_DATE, UPDATED_DATE)
SELECT SEQ_COMMON_REPLY_TEMPLATE.NEXTVAL, '환불 안내', 
       '안녕하세요. 고객님
       
환불 요청 관련하여 안내드립니다.

환불 처리는 상품 회수 확인 후 영업일 기준 3-5일 이내에 진행됩니다.
결제 수단에 따라 환불 처리 기간이